playSessionEncTags = ["disableKeys",
                      "debug",
                      "offuscate",
                      "isOwner",
                      "courseid",
                      "enrolledcourseid",
                      "disableaccess",
                      "isLive",
                      "signedurl",
                      "liveUrl",
                      "user_email",
                      "userip",
                      "cdnName",
                      "coursedetails",
                      "course",
                      "session",
                      "chapter",
                      "ContentHeading",
                      "bucketname",
                      "videokey",
                      "keyid",
                      "key",]


