# Generated by Django 2.0.4 on 2018-04-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Course')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Session')),
            ],
        ),
    ]
