# Generated by Django 2.0.4 on 2018-04-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180429_1442'),
        ('profiles', '0009_auto_20180429_1154'),
    ]

    operations = [
    ]
