# Generated by Django 2.0.4 on 2018-05-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_merge_20180429_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='coursepattern',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursepattern',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CoursePattern',
        ),
        migrations.DeleteModel(
            name='EnrolledCourse',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
